import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'
import './assets/main.css'

// Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faUser,
  faCircleExclamation,
  faTriangleExclamation,
  faBars,
  faXmark,
  faSort,
  faSortUp,
  faHome,
  faCar,
  faCarSide,
  faMotorcycle,
  faIdCard,
  faFileContract,
  faGear,
  faSignOutAlt,
  faBell,
  faBellSlash,
  faSearch,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faArrowUp,
  faCheckCircle,
  faExclamationCircle,
  faHistory,
  faUserCircle,
  faAddressBook,
  faEdit,
  faCheck,
  faCheckDouble,
  faTimes,
  faCamera,
  faArrowLeft,
  faInfoCircle,
  faHeartbeat,
  faUsers,
  faBuilding,
  faTrash,
  faClipboardList,
  faCalendar,
  faMapMarkerAlt,
  faCog,
  faCreditCard,
  faTrashAlt,
  faFilter,
  faTag,
  faFile,
  faFileAlt,
  faCalendarAlt,
  faClock,
  faInfo,
  faPrint,
  faMoneyBillWave,
  faDownload,
  faPalette,
  faCalendarCheck,
  faCalendarTimes,
  faTachometerAlt,
} from '@fortawesome/free-solid-svg-icons'
import { faGoogle } from '@fortawesome/free-brands-svg-icons'

// Add icons to the library
library.add(
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faUser,
  faGoogle,
  faCircleExclamation,
  faTriangleExclamation,
  faBars,
  faUserCircle,
  faAddressBook,
  faEdit,
  faCheck,
  faCheckDouble,
  faTimes,
  faCamera,
  faArrowLeft,
  faInfoCircle,
  faHeartbeat,
  faUsers,
  faBuilding,
  faMapMarkerAlt,
  faXmark,
  faHome,
  faCar,
  faCarSide,
  faMotorcycle,
  faIdCard,
  faFileContract,
  faGear,
  faSignOutAlt,
  faBell,
  faBellSlash,
  faSearch,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faArrowUp,
  faCheckCircle,
  faExclamationCircle,
  faHistory,
  faCog,
  faCreditCard,
  faTrashAlt,
  faFilter,
  faSort,
  faSortUp,
  faTrash,
  faTag,
  faFile,
  faFileAlt,
  faCalendar,
  faCalendarAlt,
  faClock,
  faInfo,
  faPrint,
  faClipboardList,
  faMoneyBillWave,
  faDownload,
  faPalette,
  faCalendarCheck,
  faCalendarTimes,
  faTachometerAlt,
)

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.component('font-awesome-icon', FontAwesomeIcon)

app.mount('#app')
